import type { NextPage } from "next";
import Head from "next/head";

// Components
import Button from "../components/Button";

// Styles
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="http://fonts.cdnfonts.com/css/circular-std"
          rel="stylesheet"
        />
      </Head>

      <main>
        <Button primary>Algren Primary</Button>
        <Button secondary>Algren Secondary</Button>
      </main>
    </div>
  );
};

export default Home;
